#ifndef KEYGENERATOR_H
#define KEYGENERATOR_H

#include <QString>
#include <QByteArray>


/**
 * @brief The KeyGenerator class
 *
 * This class generates random private and public keys.
 * Also it converts public key to address.
 *
 * @author defolter
 */
class KeyGenerator
{
public:

    //! Method generates random private key and returns QByteArray
    //! @return data of private key
    static QByteArray generatePrivateKey();

    //! Method generates public key from private key
    //! @param privateKey QByteArray with private key data
    //! @return data of public key
    static QByteArray generatePublicKey(QByteArray privateKey);

    //! Method converts public key to address
    //! @param publicKey QByteArray with public key data
    //! @return data of address
    static QByteArray generateAddress(QByteArray publicKey);

    //! Method checks whether address was generated by given public key
    //! @param publicKey data of public key
    //! @param address data of address
    //! @return true if was generated, else false
    static bool checkAddress(QByteArray address, QByteArray publicKey);


};

#endif // KEYGENERATOR_H
